#! /usr/bin/env bash
#
# delayed-shutdown: Delays shutdown if the no-shutdown lock file exists
#
# version: 1.0
#
# Copyright (c) 2008 George Notaras <gnot [at] g-loaded.eu>, CodeTRAX.org
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# chkconfig: 2345 0 0
#
# description: delayed-shutdown delays the shutdown procedure as long as a pre-
#              defined lockfile (no-shutdown lockfile) exists. The no-shutdown
#              lockfile should be set whenever a running process, for instance
#              a backup script, should not be interrupted by a system shutdown
#              or reboot. When started, this script has no impact on system
#              performance.
#
## BEGIN INIT INFO
# Provides: delayed-shutdown
# Default-Start: 2 3 4 5
# Default-Stop: 0 6
# Required-Start:
# Should-Start:
# Short-Description: Delays shutdown if the no-shutdown lock file exists
# Description: delayed-shutdown delays the shutdown procedure as long as a pre-
#              defined lockfile (no-shutdown lockfile) exists. The no-shutdown
#              lockfile should be set whenever a running process, for instance
#              a backup script, should not be interrupted by a system shutdown
#              or reboot. When started, this script has no impact on system
#              performance.
## END INIT INFO
#
# Usage:
#     In order to delay the shutdown process until your software finishes its
#     operation, you should create the no-shutdown lock file:
#
#         /var/lock/noshutdown.lock
#
#     Then let your software do its job and, when finished, delete the no-
#     shutdown lock file. In case of a script that would be:
#
#     touch /var/lock/noshutdown.lock
#     ... [script is working] ...
#     rm -f /var/lock/noshutdown.lock
#
#     Please note that this does not support multiple concurrent applications.
#     If you need that functionality and can live with serialized execution
#     you can use the lockfile utility (shipped with procmail).

# Settings BEGIN
noshutdownlockdir="/var/lock/noshutdown/"
# time values in seconds
delay=1
timeout=0 # a value less than 1 means indefinite
# Settings END

# Source function library.
. /lib/lsb/init-functions

RETVAL=0
prog="delayed-shutdown"
lockdir="/var/lock/subsys/"

ensure_lockfile () {
  if [ ! -e "$lockdir" ]; then
    lockdir="/var/run/"
  fi
  mkdir -p "$lockdir" > /dev/null 2>&1
  if [ ! -e "$lockdir" ]; then
    log_failure_msg "Lockdir \"$lockdir\" does not exist"
    exit 1
  fi
  lockfile="$lockdir$prog"
}

is_locked () {
  stale_file=""
  # legacy file
  if test -e /var/lock/noshutdown.lock ; then
    stale_file="/var/lock/noshutdown.lock"
    return 0
  fi
  for f in ${noshutdownlockdir}*lock ; do
    if test -e "$f" ; then
      stale_file="$f"
      return 0
    fi
  done
  return 1
}

start() {
  log_daemon_msg "Starting $prog"
  if [ -e $lockfile ] ; then
    RETVAL=1
    log_end_msg $RETVAL
    log_warning_msg "Apparently already running"
  else
    ret=$( { touch $lockfile && mkdir -p "$noshutdownlockdir" ; } 2>&1 )
    RETVAL=$?
    log_end_msg $RETVAL
    if [ "$RETVAL" -ne 0 ]; then
      log_warning_msg "Could not initialize $prog: $ret"
    fi
  fi
}

stop() {
  log_daemon_msg "Stopping $prog and waiting for important programs to finish"
  if [ -e $lockfile ] ; then
    rm -f $lockfile
    # Delay shutdown until $noshutdownlockfile is gone
    end=$( date --date="$timeout sec" +%s )
    while is_locked ; do
      if [ "$timeout" -gt 0 ] && [ $(date +%s) -ge "$end" ]; then
        message="Sorry, time ran out after $timeout seconds. Ignoring stale lock file \"$stale_file\"."
        RETVAL=1
        log_end_msg $RETVAL
        log_failure_msg $message
        logger -t $prog $message
        #wall $message
        return
      fi
      sleep $delay
    done
    log_end_msg $RETVAL
  else
    RETVAL=1
    log_end_msg $RETVAL
    log_warning_msg "Apparently $prog is not activated."
  fi
}

dostatus() {
  if [ -e $lockfile ] ; then
    echo "$prog is started."
  else
    echo "$prog is stopped."
  fi
}

restart() {
  stop
  start
}

restop() {
  start
  stop
}

condrestart() {
  [ -e $lockfile ] && restart
}

ensure_lockfile

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    dostatus
    ;;
  restart|reload)
    restart
    ;;
  restop)
    restop
    ;;
  condrestart)
    condrestart
    ;;
  *)
    echo "Usage: $(basename $0) {start|stop|status|restart|restop|reload|condrestart}"
    exit 1
esac

exit $RETVAL



